[package]
name = "neuro-adt-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neuro-types.workspace = true
quick-xml = "0.38.4"
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
url.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock.workspace = true

[lints]
workspace = true
